<?php

namespace Fr\LogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogasRepository extends EntityRepository
{
}
