<?php

namespace Fr\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadsRepository extends EntityRepository
{
}
